### ISSUE TITLE
this plugin is not working in APP_ENV=prod

### ISSUE THREAD

**Issue by akshaynikhare** [Shape-and-Shift/shopware-login-required#5] opened 2021-07-10 07:04 UTC
the plugin work perfectly in dev environment but when switched to prod it does not work

my initial Research shows that function "**onBeforeSendResponseEvent**" is never been executed in the prod environment

**Comment by ChristopherDosin** [comment] 2021-07-10 15:24
@hungmac-sw can you please check this?

**Comment by hungmac-sw** [comment] 2021-07-10 16:07
@akshaynikhare Thanks for your report. Because I implemented this function 100% on the prod environment, so I'm not sure what I missing. Did you try to clear the cache? your `SHOPWARE_HTTP_CACHE_ENABLED` is 1 or 0? and what is the Shopware version are you using?

**Comment by akshaynikhare** [comment] 2021-07-10 18:54
shopware version is   v6.4.1.2
SHOPWARE_HTTP_CACHE_ENABLED=1

I have tried it on two system :
- Docker (Dockware)
- and also my manually installing it on an ubuntu system

**Comment by hungmac-sw** [comment] 2021-07-11 08:15
@akshaynikhare HTTPcache is a big hurdle for this feature, it doesn't have enough data to use subscribers for processing under certain conditions. I used another way, can you try this one https://github.com/Shape-and-Shift/shopware-login-required/pull/6, branch name: fix/issue-5

I will release this version if it works perfectly in your prod env.

**Comment by akshaynikhare** [comment] 2021-07-12 07:39
@hungmac-sw  i tried the solution it working in a sort  , but after the server build page cache it became unsable , most of the time it did not work

i have a working solution here https://test.bemusterung-dev.helma.cloud/ ,, its not very ideal to do this , but this is the only way for now , i have been working for this in the last two week now 

please check if this helps , in my case i need to all the pages to be logged in 

what i did is i started to subscribe to kernel event for now with high priority 
` KernelEvents::REQUEST => [['onLoginRequired', 9999]],`
and then the function


```
public function directToLoginPage($request): void
    {
        $attributes = $request->attributes;
        $params = $attributes->get('_route_params');
        $route = $attributes->get('_route');
        if ($route == 'frontend.detail.page') {
            $prodId = $params['productId'];
            $url = '/account/login?redirectTo=frontend.detail.page&redirectParameters=%7B"productId":"' . $prodId . '"%7D';
            $rout = new RedirectResponse($url);
            $rout->setTargetUrl($url);
            $rout->send();
        }
        if ($route == 'frontend.navigation.page') {
            $navId = $params['navigationId'];
            $url = '/account/login?redirectTo=frontend.navigation.page&redirectParameters=%7B"navigationId":"' . $navId . '"%7D';
            $rout = new RedirectResponse($url);
            $rout->setTargetUrl($url);
            $rout->send();
        }
    } 

    public function onLoginRequired(RequestEvent $event): void
    {
        $request = $event->getRequest();
        $attributes = $request->attributes;
        $params = $attributes->get('_route_params');
        $route = $attributes->get('_route');
        if (isset($_SERVER['SHOPWARE_HTTP_CACHE_ENABLED'])) {
            if ($_SERVER['SHOPWARE_HTTP_CACHE_ENABLED']) {
                $cacheState = $request->cookies->get('sw-states');
                if (!empty($cacheState)) {
                    if (!str_contains($cacheState, CacheResponseSubscriber::STATE_LOGGED_IN)) {
                        $this->directToLoginPage($request);
                    }
                } else {
                    $this->directToLoginPage($request);
                }
            }
        }
    }
```

then in the navigation and other twig template 

```
    {% if subTreeItem.category.translated.customFields.custom_category_field_only_logged %}
                {% if context.customer %}
                    <a class="nav-item nav-link {% if id is same as(page.header.navigation.active.id) %} active{% endif %}"
                        href="{% if link %}{{ link }}{% else %}{{ seoUrl('frontend.navigation.page', { navigationId: id }) }}{% endif %}"
                        itemprop="url"
                        title="{{ name }}">
                        <span itemprop="name">{{ name }}</span>
                    </a>

                {% else %}
                    <a class="nav-item nav-link {% if id is same as(page.header.navigation.active.id) %} active{% endif %}"
                       href="{{ path('frontend.account.login.page', {redirectTo: 'frontend.navigation.page', redirectParameters:'{"navigationId":"'~id~'"}'}) }}"
                        itemprop="url"
                        title="{{ name }}">
                        <span itemprop="name">{{ name }}</span>
                    </a>
                {% endif %}
            {% else %}
                <a class="nav-item nav-link {% if id is same as(page.header.navigation.active.id) %} active{% endif %}"
                    href="{% if link %}{{ link }}{% else %}{{ seoUrl('frontend.navigation.page', { navigationId: id }) }}{% endif %}"
                    itemprop="url"
                    title="{{ name }}">
                    <span itemprop="name">{{ name }}</span>
                </a>
            {% endif %}
```

**Comment by hungmac-sw** [comment] 2021-07-12 08:01
@akshaynikhare yeah, it's working in a sort. Because I want to get the group Id of the user. In my case, your code isn't fixed. In your case, you don't need the groupId so you are also able to use `HttpCacheGenerateKeyEvent` instead of `KernelEvents::REQUEST`.

The strange thing is `onBeforeSendResponseEvent` is always working for me, I don't know why in your case it doesn't.
Very such when the context disabled when the HttpCache is enabled

**Comment by akshaynikhare** [comment] 2021-07-12 08:04
@hungmac-sw  can you try to use Docker [Dockware ](https://hub.docker.com/r/dockware/dev), may be there is some thing in the environment setup that we are missing

**Comment by hungmac-sw** [comment] 2021-07-12 08:05
@akshaynikhare Yes, I will make a setup with Dockware and tell you soon about the result

**Comment by hungmac-sw** [comment] 2021-07-12 15:39
@akshaynikhare Could you help me check something on your end? I suspect that somehow your case is running to this condition https://github.com/shopware/platform/blob/trunk/src/Core/HttpKernel.php#L164 by some plugins, I guess. 
To elucidate, just need to change `onBeforeSendResponseEvent` to `BeforeSendRedirectResponseEvent`

If your [code](https://github.com/Shape-and-Shift/shopware-login-required/issues/5#issuecomment-878048268) is running parallel with my code then It will be incompatible because you're using redirect in every categories, I guess

**Comment by akshaynikhare** [comment] 2021-07-12 16:38
@hungmac-sw  you suggestion does work also , but this time the event was fired at least 

but if you set up a dockware image  , from attached setup
[SW_test48.zip](https://github.com/Shape-and-Shift/shopware-login-required/files/6803003/SW_test48.zip)


what worked for me was this in main [branch ](https://github.com/Shape-and-Shift/shopware-login-required)

```
    private function directToLoginPage(Request $request): void
    {
        $storefrontUrl = $request->attributes->get(RequestTransformer::STOREFRONT_URL);
        $loginUrl = $storefrontUrl . '/account/login';

        header('Location: ' . $loginUrl);
        
       die();   // this worked for me for the 
    }
```

**Comment by hungmac-sw** [comment] 2021-07-13 15:18
@akshaynikhare I tried to run with you the attached setup, In my end, it showed the error with $SESSION['SHOPWARE_HTTP_CACHE_ENABLED] because it's not existing in the env config. Everything else works fine, I don't need to add die();`

Sorry, we can't support you with your issue because we can't reproduce it on the [stable](https://www.shopware.com/en/changelog/#6-4-2-1) version.

**Comment by akshaynikhare** [comment] 2021-07-13 15:28
You need to add that in .env file 

 SHOPWARE_HTTP_CACHE_ENABLED=1

And are you sure you are using the same file I attached in the previous comment

**Comment by hungmac-sw** [comment] 2021-07-13 17:00
@akshaynikhare Yes, I'm sure. with added `SHOPWARE_HTTP_CACHE_ENABLED=1` also test on stable version [here](https://www.shopware.com/en/changelog/#6-4-2-1) run on valet+

![dockware-test](https://user-images.githubusercontent.com/60767402/125494552-9852a011-b0a1-4f3e-a2b1-3908fbcd77a1.png)

**Closed as completed** 2021-07-16 04:43 UTC
